config/routes.rb
require 'sidekiq/web'
require 'api/api'

Gitlab::Application.routes.draw do
  #
  # Search
  #
  get 'search' => "search#show"

  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web, at: "/admin/sidekiq", as: :sidekiq
  end

  # Enable Grack support
  mount Grack::Bundle.new({
    git_path:     Gitlab.config.git.bin_path,
    project_root: Gitlab.config.gitlab_shell.repos_path,
    upload_pack:  Gitlab.config.gitlab_shell.upload_pack,
    receive_pack: Gitlab.config.gitlab_shell.receive_pack
  }), at: '/', constraints: lambda { |request| /[-\/\w\.]+\.git\//.match(request.path_info) }

  #
  # Help
  #
  get 'help'                => 'help#index'
  get 'help/api'            => 'help#api'
  get 'help/api/:category'  => 'help#api', as: 'help_api_file'
  get 'help/markdown'       => 'help#markdown'
  get 'help/permissions'    => 'help#permissions'
  get 'help/public_access'  => 'help#public_access'
  get 'help/raketasks'      => 'help#raketasks'
  get 'help/ssh'            => 'help#ssh'
  get 'help/system_hooks'   => 'help#system_hooks'
  get 'help/web_hooks'      => 'help#web_hooks'
  get 'help/workflow'       => 'help#workflow'
  get 'help/shortcuts'

  #
  # Global snippets
  #
  resources :snippets do
    member do
      get "raw"
    end
  end
  get "/s/:username" => "snippets#user_index", as: :user_snippets, constraints: { username: /.*/ }

  #
  # Public namespace
  #
  namespace :public do
    resources :projects, only: [:index]
    resources :projects, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }, only: [:show]

    root to: "projects#index"
  end

  #
  # Attachments serving
  #
  get 'files/:type/:id/:filename' => 'files#download', constraints: { id: /\d+/, type: /[a-z]+/, filename:  /.+/ }

  #
  # Admin Area
  #
  namespace :admin do
    resources :users, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ } do
      member do
        put :team_update
        put :block
        put :unblock
      end
    end

    resources :groups, constraints: { id: /[^\/]+/ } do
      member do
        put :project_teams_update
      end
    end

    resources :hooks, only: [:index, :create, :destroy] do
      get :test
    end

    resource :logs, only: [:show]
    resource :background_jobs, controller: 'background_jobs', only: [:show]
    resources :projects, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }, only: [:index, :show]
    root to: "dashboard#index"
  end

  get "errors/githost"

  #
  # Profile Area
  #
  resource :profile, only: [:show, :update] do
    member do
      get :account
      get :history
      get :token
      get :design

      put :update_password
      put :reset_private_token
      put :update_username
    end

    scope module: :profiles do
      resource :notifications, only: [:show, :update]
      resource :password, only: [:new, :create]
      resources :keys
      resources :groups, only: [:index] do
        member do
          delete :leave
        end
      end
    end
  end

  match "/u/:username" => "users#show", as: :user, constraints: { username: /.*/ }



  #
  # Dashboard Area
  #
  resource :dashboard, controller: "dashboard", only: [:show] do
    member do
      get :projects
      get :issues
      get :merge_requests
    end
  end

  #
  # Groups Area
  #
  resources :groups, constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}  do
    member do
      get :issues
      get :merge_requests
      get :members
    end

    resources :users_groups, only: [:create, :update, :destroy]
  end

  resources :projects, constraints: { id: /[^\/]+/ }, only: [:new, :create]

  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks, registrations: :registrations }

  #
  # Project Area
  #
  resources :projects, constraints: { id: /[a-zA-Z.0-9_\-]+\/[a-zA-Z.0-9_\-]+/ }, except: [:new, :create, :index], path: "/" do
    member do
      put :transfer
      post :fork
      get :autocomplete_sources
    end

    scope module: :projects do
      resources :blob,    only: [:show], constraints: {id: /.+/}
      resources :raw,    only: [:show], constraints: {id: /.+/}
      resources :tree,    only: [:show], constraints: {id: /.+/, format: /(html|js)/ }
      resources :edit_tree,    only: [:show, :update], constraints: {id: /.+/}, path: 'edit'
      resources :commit,  only: [:show], constraints: {id: /[[:alnum:]]{6,40}/}
      resources :commits, only: [:show], constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}
      resources :compare, only: [:index, :create]
      resources :blame,   only: [:show], constraints: {id: /.+/}
      resources :network,   only: [:show], constraints: {id: /(?:[^.]|\.(?!json$))+/, format: /json/}
      resources :graphs, only: [:show], constraints: {id: /(?:[^.]|\.(?!json$))+/, format: /json/}
      match "/compare/:from...:to" => "compare#show", as: "compare", via: [:get, :post], constraints: {from: /.+/, to: /.+/}

        resources :snippets, constraints: {id: /\d+/} do
          member do
            get "raw"
          end
        end

      resources :wikis, only: [:show, :edit, :destroy, :create], constraints: {id: /[a-zA-Z.0-9_\-]+/} do
        collection do
          get :pages
          put ':id' => 'wikis#update'
          get :git_access
        end

        member do
          get "history"
        end
      end

      resource :wall, only: [:show], constraints: {id: /\d+/} do
        member do
          get 'notes'
        end
      end

      resource :repository, only: [:show] do
        member do
          get "stats"
          get "archive"
        end
      end

      resources :services, constraints: { id: /[^\/]+/ }, only: [:index, :edit, :update] do
        member do
          get :test
        end
      end

      resources :deploy_keys, constraints: {id: /\d+/} do
        member do
          put :enable
          put :disable
        end
      end

      resources :branches, only: [:index, :new, :create, :destroy], constraints: { id: /[a-zA-Z.\/0-9_\-#%+]+/ } do
        collection do
          get :recent
        end
      end

      resources :tags, only: [:index, :new, :create, :destroy], constraints: { id: /[a-zA-Z.\/0-9_\-#%+]+/ }
      resources :protected_branches, only: [:index, :create, :destroy], constraints: { id: /[a-zA-Z.\/0-9_\-#%+]+/ }

      resources :refs, only: [] do
        collection do
          get "switch"
        end

        member do
          # tree viewer logs
          get "logs_tree", constraints: { id: /[a-zA-Z.\/0-9_\-#%+]+/ }
          get "logs_tree/:path" => "refs#logs_tree",
            as: :logs_file,
            constraints: {
              id:   /[a-zA-Z.0-9\/_\-#%+]+/,
              path: /.*/
            }
        end
      end

      resources :merge_requests, constraints: {id: /\d+/}, except: [:destroy] do
        member do
          get :diffs
          get :automerge
          get :automerge_check
          get :ci_status
        end

        collection do
          get :branch_from
          get :branch_to
          get :update_branches
        end
      end

      resources :hooks, only: [:index, :create, :destroy], constraints: {id: /\d+/} do
        member do
          get :test
        end
      end

      resources :team, controller: 'team_members', only: [:index]
      resources :milestones, except: [:destroy], constraints: {id: /\d+/}

      resources :labels, only: [:index] do
        collection do
          post :generate
        end
      end

      resources :issues, constraints: {id: /\d+/}, except: [:destroy] do
        collection do
          post  :bulk_update
        end
      end

      resources :team_members, except: [:index, :edit], constraints: { id: /[a-zA-Z.\/0-9_\-#%+]+/ } do
        collection do

          # Used for import team
          # from another project
          get :import
          post :apply_import
        end
      end

      resources :notes, only: [:index, :create, :destroy, :update], constraints: {id: /\d+/} do
        member do
          delete :delete_attachment
        end

        collection do
          post :preview
        end
      end
    end
  end

  root to: "dashboard#show"
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
  before_filter :project, only: [:edit, :show, :update, :destroy, :team_update]

  def index
    owner_id = params[:owner_id]
    user = User.find_by_id(owner_id)

    @projects = user ? user.owned_projects : Project.scoped
    @projects = @projects.where(public: true) if params[:public_only].present?
    @projects = @projects.with_push if params[:with_push].present?
    @projects = @projects.abandoned if params[:abandoned].present?
    @projects = @projects.search(params[:name]) if params[:name].present?
    @projects = @projects.includes(:namespace).order("namespaces.path, projects.name ASC").page(params[:page]).per(20)
  end

  def show
    @repository = @project.repository
    @group = @project.group
  end

  protected

  def project
    id = params[:project_id] || params[:id]

    @project = Project.find_with_namespace(id)
    @project || render_404
  end
end

app/controllers/projects/application_controller.rb
class Projects::ApplicationController < ApplicationController
  before_filter :project
  before_filter :repository
  layout 'projects'
end

app/controllers/projects/blame_controller.rb
# Controller for viewing a file's blame
class Projects::BlameController < Projects::ApplicationController
  include ExtractsPath

  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_code_access!
  before_filter :require_non_empty_project

  def show
    @blob = Gitlab::Git::Blob.new(@repository, @commit.id, @ref, @path)
    @blame = Gitlab::Git::Blame.new(project.repository, @commit.id, @path)
  end
end

app/controllers/projects/blob_controller.rb
# Controller for viewing a file's blame
class Projects::BlobController < Projects::ApplicationController
  include ExtractsPath

  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_code_access!
  before_filter :require_non_empty_project

  def show
    @blob = Gitlab::Git::Blob.new(@repository, @commit.id, @ref, @path)
  end
end

app/controllers/projects/branches_controller.rb
class Projects::BranchesController < Projects::ApplicationController
  # Authorize
  before_filter :authorize_read_project!
  before_filter :require_non_empty_project

  before_filter :authorize_code_access!
  before_filter :authorize_push!, only: [:create]
  before_filter :authorize_admin_project!, only: [:destroy]

  def index
    @branches = Kaminari.paginate_array(@repository.branches).page(params[:page]).per(30)
  end

  def recent
    @branches = @repository.recent_branches
  end

  def create
    @repository.add_branch(params[:branch_name], params[:ref])

    if new_branch = @repository.find_branch(params[:branch_name])
      Event.create_ref_event(@project, current_user, new_branch, 'add')
    end

    redirect_to project_branches_path(@project)
  end

  def destroy
    branch = @repository.find_branch(params[:id])

    if branch && @repository.rm_branch(branch.name)
      Event.create_ref_event(@project, current_user, branch, 'rm')
    end

    respond_to do |format|
      format.html { redirect_to project_branches_path(@project) }
      format.js { render nothing: true }
    end
  end
end

app/controllers/projects/commit_controller.rb
# Controller for a specific Commit
#
# Not to be confused with CommitsController, plural.
class Projects::CommitController < Projects::ApplicationController
  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_code_access!
  before_filter :require_non_empty_project

  def show
    result = CommitLoadContext.new(project, current_user, params).execute

    @commit = result[:commit]

    if @commit.nil?
      git_not_found!
      return
    end

    @suppress_diff = result[:suppress_diff]
    @force_suppress_diff = result[:force_suppress_diff]

    @note        = result[:note]
    @line_notes  = result[:line_notes]
    @notes_count = result[:notes_count]
    @target_type = :commit
    @target_id   = @commit.id

    @comments_allowed = @reply_allowed = true
    @comments_target  = { noteable_type: 'Commit',
                          commit_id: @commit.id }

    respond_to do |format|
      format.html do
        if result[:status] == :huge_commit
          render "huge_commit" and return
        end
      end

      format.diff  { render text: @commit.to_diff }
      format.patch { render text: @commit.to_patch }
    end
  end
end

app/controllers/projects/commits_controller.rb
require "base64"

class Projects::CommitsController < Projects::ApplicationController
  include ExtractsPath

  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_code_access!
  before_filter :require_non_empty_project

  def show
    @repo = @project.repository
    @limit, @offset = (params[:limit] || 40), (params[:offset] || 0)

    @commits = @repo.commits(@ref, @path, @limit, @offset)

    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.atom { render layout: false }
    end
  end
end

app/controllers/projects/compare_controller.rb
class Projects::CompareController < Projects::ApplicationController
  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_code_access!
  before_filter :require_non_empty_project

  def index
  end

  def show
    compare = Gitlab::Git::Compare.new(@repository.raw_repository, params[:from], params[:to])

    @commits       = compare.commits
    @commit        = compare.commit
    @diffs         = compare.diffs
    @refs_are_same = compare.same
    @line_notes    = []

    diff_line_count = Commit::diff_line_count(@diffs)
    @suppress_diff = Commit::diff_suppress?(@diffs, diff_line_count) && !params[:force_show_diff]
    @force_suppress_diff = Commit::diff_force_suppress?(@diffs, diff_line_count)
  end

  def create
    redirect_to project_compare_path(@project, params[:from], params[:to])
  end
end

app/controllers/projects/deploy_keys_controller.rb
class Projects::DeployKeysController < Projects::ApplicationController
  respond_to :html

  # Authorize
  before_filter :authorize_admin_project!

  layout "project_settings"

  def index
    @enabled_keys = @project.deploy_keys.all
    @available_keys = available_keys - @enabled_keys
  end

  def show
    @key = @project.deploy_keys.find(params[:id])
  end

  def new
    @key = @project.deploy_keys.new

    respond_with(@key)
  end

  def create
    @key = DeployKey.new(params[:deploy_key])

    if @key.valid? && @project.deploy_keys << @key
      redirect_to project_deploy_keys_path(@project)
    else
      render "new"
    end
  end

  def destroy
    @key = @project.deploy_keys.find(params[:id])
    @key.destroy

    respond_to do |format|
      format.html { redirect_to project_deploy_keys_url }
      format.js { render nothing: true }
    end
  end

  def enable
    project.deploy_keys << available_keys.find(params[:id])

    redirect_to project_deploy_keys_path(@project)
  end

  def disable
    @project.deploy_keys_projects.where(deploy_key_id: params[:id]).last.destroy

    redirect_to project_deploy_keys_path(@project)
  end

  protected

  def available_keys
    @available_keys ||= current_user.accessible_deploy_keys
  end
end

app/controllers/projects/edit_tree_controller.rb
# Controller for edit a repository's file
class Projects::EditTreeController < Projects::ApplicationController
  include ExtractsPath

  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_code_access!
  before_filter :require_non_empty_project

  before_filter :edit_requirements, only: [:show, :update]

  def show
    @last_commit = Gitlab::Git::Commit.last_for_path(@project.repository, @ref, @path).sha
  end

  def update
    edit_file_action = Gitlab::Satellite::EditFileAction.new(current_user, @project, @ref, @path)
    updated_successfully = edit_file_action.commit!(
      params[:content],
      params[:commit_message],
      params[:last_commit]
    )

    if updated_successfully
      redirect_to project_blob_path(@project, @id), notice: "Your changes have been successfully commited"
    else
      flash[:notice] = "Your changes could not be commited, because the file has been changed"
      render :show
    end
  end

  private

  def edit_requirements
    @blob = Gitlab::Git::Blob.new(@repository, @commit.id, @ref, @path)

    unless @blob.exists? && @blob.text?
      redirect_to project_blob_path(@project, @id), notice: "You can only edit text files"
    end

    allowed = if project.protected_branch? @ref
                can?(current_user, :push_code_to_protected_branches, project)
              else
                can?(current_user, :push_code, project)
              end

    return access_denied! unless allowed
  end
end

app/controllers/projects/graphs_controller.rb
class Projects::GraphsController < Projects::ApplicationController
  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_code_access!
  before_filter :require_non_empty_project

  def show
    respond_to do |format|
      format.html
      format.js do
        fetch_graph
      end
    end
  end

  private

  def fetch_graph
    @log = @project.repository.graph_log.to_json
    @success = true
  rescue => ex
    @log = []
    @success = false
  end
end

app/views/projects/notes/_diff_note_link.html.haml
- note = @project.notes.new(@comments_target.merge({ line_code: line_code }))
= link_to "",
          "javascript:;",
          class: "add-diff-note js-add-diff-note-button",
          data: { noteable_type: note.noteable_type,
                  noteable_id:   note.noteable_id,
                  commit_id:     note.commit_id,
                  line_code:     note.line_code,
                  discussion_id: note.discussion_id },
          title: "Add a comment to this line"

app/views/projects/notes/_diff_notes_with_reply.html.haml
- note = notes.first # example note
-# Check if line want not changed since comment was left
- if !defined?(line) || line == note.diff_line
  %tr.notes_holder
    %td.notes_line{ colspan: 2 }
      %span.btn.disabled
        %i.icon-comment
        = notes.count
    %td.notes_content
      %ul.notes{ rel: note.discussion_id }
        = render notes

      = render "projects/notes/discussion_reply_button", note: note

app/views/projects/notes/_discussion.html.haml
- note = discussion_notes.first
.discussion.js-details-container.js-toggler-container.open{ class: note.discussion_id }
  .discussion-header
    .discussion-actions
      = link_to "javascript:;", class: "js-details-target turn-on js-toggler-target" do
        %i.icon-eye-close
        Hide discussion
      = link_to "javascript:;", class: "js-details-target turn-off js-toggler-target" do
        %i.icon-eye-open
        Show discussion
    = image_tag gravatar_icon(note.author_email), class: "avatar s32"
    %div
      = link_to_member(@project, note.author, avatar: false)
      - if note.for_merge_request?
        - if note.diff
          started a discussion on this merge request diff
          = link_to_merge_request_diff_line_note(note)
        - else
          started
          %strong
            %i.icon-remove
            outdated
          discussion on this merge request diff
      - elsif note.for_commit?
        started a discussion on commit
        #{link_to note.noteable.short_id, project_commit_path(note.project, note.noteable)}
        = link_to_commit_diff_line_note(note) if note.for_diff_line?
      - else
        %cite.cgray started a discussion
    %div
      - last_note = discussion_notes.last
      last updated by
      = link_to_member(@project, last_note.author, avatar: false)
      %span.discussion-last-update
        = time_ago_in_words(last_note.updated_at)
        ago
  .discussion-body
    - if note.for_diff_line?
      - if note.active?
        .content
          .file= render "projects/notes/discussion_diff", discussion_notes: discussion_notes, note: note
      - else
        = link_to 'show outdated discussion', '#', class: 'js-show-outdated-discussion'
        %div.hide.outdated-discussion
          .content
            .notes{ rel: discussion_notes.first.discussion_id }
              = render discussion_notes


    - else
      .content
        .notes{ rel: discussion_notes.first.discussion_id }
          = render discussion_notes
        = render "projects/notes/discussion_reply_button", note: discussion_notes.first

    -# will be shown when the other one is hidden
    .discussion-hidden.content.hide
      .note
        %em Hidden discussion.
        = link_to "javascript:;", class: "js-details-target js-toggler-target" do
          %i.icon-eye-open
          Show

app/views/projects/notes/_discussion_diff.html.haml
- diff = note.diff
.header
  - if diff.deleted_file
    %span= diff.old_path
  - else
    %span= diff.new_path
    - if diff.a_mode && diff.b_mode && diff.a_mode != diff.b_mode
      %span.file-mode= "#{diff.a_mode} → #{diff.b_mode}"
  %br/
.content
  %table
    - each_diff_line_near(diff, note.diff_file_index, note.line_code) do |line, type, line_code, line_new, line_old|
      %tr.line_holder{ id: line_code }
        - if type == "match"
          %td.old_line= "..."
          %td.new_line= "..."
          %td.line_content.matched= line
        - else
          %td.old_line= raw(type == "new" ? "&nbsp;" : line_old)
          %td.new_line= raw(type == "old" ? "&nbsp;" : line_new)
          %td.line_content{class: "noteable_line #{type} #{line_code}", "line_code" => line_code}= raw "#{line} &nbsp;"

          - if line_code == note.line_code
            = render "projects/notes/diff_notes_with_reply", notes: discussion_notes

app/views/projects/notes/_discussion_reply_button.html.haml
= link_to "javascript:;",
          class: "btn reply-btn js-discussion-reply-button",
          data: { noteable_type: note.noteable_type,
                  noteable_id:   note.noteable_id,
                  commit_id:     note.commit_id,
                  line_code:     note.line_code,
                  discussion_id: note.discussion_id },
          title: "Add a reply" do
  %i.icon-comment
  Reply

app/views/projects/notes/_form.html.haml
= form_for [@project, @note], remote: true, html: { multipart: true, id: nil, class: "new_note js-new-note-form common-note-form" } do |f|

  = note_target_fields
  = f.hidden_field :commit_id
  = f.hidden_field :line_code
  = f.hidden_field :noteable_id
  = f.hidden_field :noteable_type

  .note_text_and_preview.js-toggler-container
    %a.js-note-preview-button.js-toggler-target.turn-off{ href: "javascript:;", title: "Preview", data: {url: preview_project_notes_path(@project)} }
      %i.icon-eye-open
    %a.js-note-edit-button.js-toggler-target.turn-off{ href: "javascript:;", title: "Edit" }
      %i.icon-edit

    = f.text_area :note, size: 255, class: 'note_text js-note-text js-gfm-input turn-on'
    .note_preview.js-note-preview.turn-off

  .hint
    .pull-right Comments are parsed with #{link_to "GitLab Flavored Markdown", help_markdown_path, target: '_blank'}.
  .clearfix

  .note-form-actions
    .buttons
      = f.submit 'Add Comment', class: "btn comment-btn grouped js-comment-button"
      = yield(:note_actions)

      %a.btn.grouped.js-close-discussion-note-form Cancel

    .note-form-option
      %a.choose-btn.btn.btn-small.js-choose-note-attachment-button
        %i.icon-paper-clip
        %span Choose File ...
      &nbsp;
      %span.file_name.js-attachment-filename File name...
      = f.file_field :attachment, class: "js-note-attachment-input hide"

    .clearfix

app/views/projects/notes/_form_errors.html.haml
.error-message.js-errors
  - note.errors.full_messages.each do |msg|
    %div= msg

app/views/projects/notes/_note.html.haml
%li{ id: dom_id(note), class: dom_class(note), data: { discussion: note.discussion_id } }
  .note-header
    .note-actions
      = link_to "##{dom_id(note)}", name: dom_id(note) do
        %i.icon-link
        Link here
      &nbsp;
      - if(note.author_id == current_user.id) || can?(current_user, :admin_note, @project)
        = link_to "#", title: "Edit comment", class: "js-note-edit" do
          %i.icon-edit
          Edit
        &nbsp;
        = link_to project_note_path(@project, note), title: "Remove comment", method: :delete, confirm: 'Are you sure you want to remove this comment?', remote: true, class: "danger js-note-delete" do
          %i.icon-trash.cred
          Remove
    = image_tag gravatar_icon(note.author_email), class: "avatar s32"
    = link_to_member(@project, note.author, avatar: false)
    %span.note-last-update
      = note_timestamp(note)

    - if note.upvote?
      %span.vote.upvote.label.label-success
        %i.icon-thumbs-up
        \+1
    - if note.downvote?
      %span.vote.downvote.label.label-error
        %i.icon-thumbs-down
        \-1


  .note-body
    .note-text
      = preserve do
        = markdown(note.note)

    .note-edit-form
      = form_for note, url: project_note_path(@project, note), method: :put, remote: true do |f|
        = f.text_area :note, class: 'note_text js-note-text js-gfm-input turn-on'

        .form-actions
          = f.submit 'Save changes', class: "btn btn-primary btn-save"

          .note-form-option
            %a.choose-btn.btn.btn-small.js-choose-note-attachment-button
              %i.icon-paper-clip
              %span Choose File ...
            &nbsp;
            %span.file_name.js-attachment-filename File name...
            = f.file_field :attachment, class: "js-note-attachment-input hide"

          = link_to  'Cancel', "#", class: "btn btn-cancel note-edit-cancel"


  - if note.attachment.url
    .note-attachment
      - if note.attachment.image?
        = link_to note.attachment.url, target: '_blank' do
          = image_tag note.attachment.url, class: 'note-image-attach'
      .attachment.pull-right
        = link_to note.attachment.secure_url, target: "_blank" do
          %i.icon-paper-clip
          = note.attachment_identifier
          = link_to delete_attachment_project_note_path(@project, note),
            title: "Delete this attachment", method: :delete, remote: true, confirm: 'Are you sure you want to remove the attachment?', class: "danger js-note-attachment-delete" do
            %i.icon-trash.cred
  .clear

app/views/projects/notes/_notes.html.haml
- if @discussions.present?
  - @discussions.each do |discussion_notes|
    - note = discussion_notes.first
    - if note_for_main_target?(note)
      = render discussion_notes
    - else
      = render 'discussion', discussion_notes: discussion_notes
- else
  - @notes.each do |note|
    - next unless note.author
    = render note

app/views/projects/notes/_notes_with_form.html.haml
%ul#notes-list.notes
.js-notes-busy

.js-main-target-form
- if can? current_user, :write_note, @project
  = render "projects/notes/form"

:javascript
  NoteList.init("#{@target_id}", "#{@target_type}", "#{project_notes_path(@project)}");

app/views/projects/notes/create.js.haml
- if @note.valid?
  var noteHtml = "#{escape_javascript(render @note)}";

  - if note_for_main_target?(@note)
    NoteList.appendNewNote(#{@note.id}, noteHtml);
  - else
    :plain
      var firstDiscussionNoteHtml = "#{escape_javascript(render "projects/notes/diff_notes_with_reply", notes: [@note])}";
      NoteList.appendNewDiscussionNote("#{@note.discussion_id}",
                                       firstDiscussionNoteHtml,
                                       noteHtml);

- else
  var errorsHtml = "#{escape_javascript(render 'projects/notes/form_errors', note: @note)}";
  - if note_for_main_target?(@note)
    NoteList.errorsOnForm(errorsHtml);
  - else
    NoteList.errorsOnForm(errorsHtml, "#{@note.discussion_id}");

app/views/projects/notes/index.js.haml
- unless @notes.blank?
  var notesHtml = "#{escape_javascript(render 'projects/notes/notes')}";
  - new_note_ids = @notes.map(&:id)
  NoteList.setContent(#{new_note_ids}, notesHtml);