config/routes.rb
require 'sidekiq/web'
require 'api/api'

Gitlab::Application.routes.draw do
  #
  # Search
  #
  get 'search' => "search#show"

  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web, at: "/admin/sidekiq", as: :sidekiq
  end

  # Enable Grack support
  mount Grack::Bundle.new({
    git_path:     Gitlab.config.git.bin_path,
    project_root: Gitlab.config.gitlab_shell.repos_path,
    upload_pack:  Gitlab.config.gitlab_shell.upload_pack,
    receive_pack: Gitlab.config.gitlab_shell.receive_pack
  }), at: '/', constraints: lambda { |request| /[-\/\w\.]+\.git\//.match(request.path_info) }

  #
  # Help
  #
  get 'help'                => 'help#index'
  get 'help/api'            => 'help#api'
  get 'help/api/:category'  => 'help#api', as: 'help_api_file'
  get 'help/markdown'       => 'help#markdown'
  get 'help/permissions'    => 'help#permissions'
  get 'help/public_access'  => 'help#public_access'
  get 'help/raketasks'      => 'help#raketasks'
  get 'help/ssh'            => 'help#ssh'
  get 'help/system_hooks'   => 'help#system_hooks'
  get 'help/web_hooks'      => 'help#web_hooks'
  get 'help/workflow'       => 'help#workflow'
  get 'help/shortcuts'

  #
  # Global snippets
  #
  resources :snippets do
    member do
      get "raw"
    end
  end
  get "/s/:username" => "snippets#user_index", as: :user_snippets, constraints: { username: /.*/ }

  #
  # Public namespace
  #
  namespace :public do
    resources :projects, only: [:index]
    resources :projects, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }, only: [:show]

    root to: "projects#index"
  end

  #
  # Attachments serving
  #
  get 'files/:type/:id/:filename' => 'files#download', constraints: { id: /\d+/, type: /[a-z]+/, filename:  /.+/ }

  #
  # Admin Area
  #
  namespace :admin do
    resources :users, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ } do
      member do
        put :team_update
        put :block
        put :unblock
      end
    end

    resources :groups, constraints: { id: /[^\/]+/ } do
      member do
        put :project_teams_update
      end
    end

    resources :hooks, only: [:index, :create, :destroy] do
      get :test
    end

    resource :logs, only: [:show]
    resource :background_jobs, controller: 'background_jobs', only: [:show]
    resources :projects, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }, only: [:index, :show]
    root to: "dashboard#index"
  end

  get "errors/githost"

  #
  # Profile Area
  #
  resource :profile, only: [:show, :update] do
    member do
      get :account
      get :history
      get :token
      get :design

      put :update_password
      put :reset_private_token
      put :update_username
    end

    scope module: :profiles do
      resource :notifications, only: [:show, :update]
      resource :password, only: [:new, :create]
      resources :keys
      resources :groups, only: [:index] do
        member do
          delete :leave
        end
      end
    end
  end

  match "/u/:username" => "users#show", as: :user, constraints: { username: /.*/ }



  #
  # Dashboard Area
  #
  resource :dashboard, controller: "dashboard", only: [:show] do
    member do
      get :projects
      get :issues
      get :merge_requests
    end
  end

  #
  # Groups Area
  #
  resources :groups, constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}  do
    member do
      get :issues
      get :merge_requests
      get :members
    end

    resources :users_groups, only: [:create, :update, :destroy]
  end

  resources :projects, constraints: { id: /[^\/]+/ }, only: [:new, :create]

  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks, registrations: :registrations }

  #
  # Project Area
  #
  resources :projects, constraints: { id: /[a-zA-Z.0-9_\-]+\/[a-zA-Z.0-9_\-]+/ }, except: [:new, :create, :index], path: "/" do
    member do
      put :transfer
      post :fork
      get :autocomplete_sources
    end

    scope module: :projects do
      resources :blob,    only: [:show], constraints: {id: /.+/}
      resources :raw,    only: [:show], constraints: {id: /.+/}
      resources :tree,    only: [:show], constraints: {id: /.+/, format: /(html|js)/ }
      resources :edit_tree,    only: [:show, :update], constraints: {id: /.+/}, path: 'edit'
      resources :commit,  only: [:show], constraints: {id: /[[:alnum:]]{6,40}/}
      resources :commits, only: [:show], constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}
      resources :compare, only: [:index, :create]
      resources :blame,   only: [:show], constraints: {id: /.+/}
      resources :network,   only: [:show], constraints: {id: /(?:[^.]|\.(?!json$))+/, format: /json/}
      resources :graphs, only: [:show], constraints: {id: /(?:[^.]|\.(?!json$))+/, format: /json/}
      match "/compare/:from...:to" => "compare#show", as: "compare", via: [:get, :post], constraints: {from: /.+/, to: /.+/}

        resources :snippets, constraints: {id: /\d+/} do
          member do
            get "raw"
          end
        end

      resources :wikis, only: [:show, :edit, :destroy, :create], constraints: {id: /[a-zA-Z.0-9_\-]+/} do
        collection do
          get :pages
          put ':id' => 'wikis#update'
          get :git_access
        end

        member do
          get "history"
        end
      end

      resource :wall, only: [:show], constraints: {id: /\d+/} do
        member do
          get 'notes'
        end
      end

      resource :repository, only: [:show] do
        member do
          get "stats"
          get "archive"
        end
      end

      resources :services, constraints: { id: /[^\/]+/ }, only: [:index, :edit, :update] do
        member do
          get :test
        end
      end

      resources :deploy_keys, constraints: {id: /\d+/} do
        member do
          put :enable
          put :disable
        end
      end

      resources :branches, only: [:index, :new, :create, :destroy], constraints: { id: /[a-zA-Z.\/0-9_\-#%+]+/ } do
        collection do
          get :recent
        end
      end

      resources :tags, only: [:index, :new, :create, :destroy], constraints: { id: /[a-zA-Z.\/0-9_\-#%+]+/ }
      resources :protected_branches, only: [:index, :create, :destroy], constraints: { id: /[a-zA-Z.\/0-9_\-#%+]+/ }

      resources :refs, only: [] do
        collection do
          get "switch"
        end

        member do
          # tree viewer logs
          get "logs_tree", constraints: { id: /[a-zA-Z.\/0-9_\-#%+]+/ }
          get "logs_tree/:path" => "refs#logs_tree",
            as: :logs_file,
            constraints: {
              id:   /[a-zA-Z.0-9\/_\-#%+]+/,
              path: /.*/
            }
        end
      end

      resources :merge_requests, constraints: {id: /\d+/}, except: [:destroy] do
        member do
          get :diffs
          get :automerge
          get :automerge_check
          get :ci_status
        end

        collection do
          get :branch_from
          get :branch_to
          get :update_branches
        end
      end

      resources :hooks, only: [:index, :create, :destroy], constraints: {id: /\d+/} do
        member do
          get :test
        end
      end

      resources :team, controller: 'team_members', only: [:index]
      resources :milestones, except: [:destroy], constraints: {id: /\d+/}

      resources :labels, only: [:index] do
        collection do
          post :generate
        end
      end

      resources :issues, constraints: {id: /\d+/}, except: [:destroy] do
        collection do
          post  :bulk_update
        end
      end

      resources :team_members, except: [:index, :edit], constraints: { id: /[a-zA-Z.\/0-9_\-#%+]+/ } do
        collection do

          # Used for import team
          # from another project
          get :import
          post :apply_import
        end
      end

      resources :notes, only: [:index, :create, :destroy, :update], constraints: {id: /\d+/} do
        member do
          delete :delete_attachment
        end

        collection do
          post :preview
        end
      end
    end
  end

  root to: "dashboard#show"
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
  before_filter :project, only: [:edit, :show, :update, :destroy, :team_update]

  def index
    owner_id = params[:owner_id]
    user = User.find_by_id(owner_id)

    @projects = user ? user.owned_projects : Project.scoped
    @projects = @projects.where(public: true) if params[:public_only].present?
    @projects = @projects.with_push if params[:with_push].present?
    @projects = @projects.abandoned if params[:abandoned].present?
    @projects = @projects.search(params[:name]) if params[:name].present?
    @projects = @projects.includes(:namespace).order("namespaces.path, projects.name ASC").page(params[:page]).per(20)
  end

  def show
    @repository = @project.repository
    @group = @project.group
  end

  protected

  def project
    id = params[:project_id] || params[:id]

    @project = Project.find_with_namespace(id)
    @project || render_404
  end
end

app/controllers/projects/application_controller.rb
class Projects::ApplicationController < ApplicationController
  before_filter :project
  before_filter :repository
  layout 'projects'
end

app/controllers/projects/blame_controller.rb
# Controller for viewing a file's blame
class Projects::BlameController < Projects::ApplicationController
  include ExtractsPath

  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_code_access!
  before_filter :require_non_empty_project

  def show
    @blob = Gitlab::Git::Blob.new(@repository, @commit.id, @ref, @path)
    @blame = Gitlab::Git::Blame.new(project.repository, @commit.id, @path)
  end
end

app/controllers/projects/blob_controller.rb
# Controller for viewing a file's blame
class Projects::BlobController < Projects::ApplicationController
  include ExtractsPath

  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_code_access!
  before_filter :require_non_empty_project

  def show
    @blob = Gitlab::Git::Blob.new(@repository, @commit.id, @ref, @path)
  end
end

app/controllers/projects/branches_controller.rb
class Projects::BranchesController < Projects::ApplicationController
  # Authorize
  before_filter :authorize_read_project!
  before_filter :require_non_empty_project

  before_filter :authorize_code_access!
  before_filter :authorize_push!, only: [:create]
  before_filter :authorize_admin_project!, only: [:destroy]

  def index
    @branches = Kaminari.paginate_array(@repository.branches).page(params[:page]).per(30)
  end

  def recent
    @branches = @repository.recent_branches
  end

  def create
    @repository.add_branch(params[:branch_name], params[:ref])

    if new_branch = @repository.find_branch(params[:branch_name])
      Event.create_ref_event(@project, current_user, new_branch, 'add')
    end

    redirect_to project_branches_path(@project)
  end

  def destroy
    branch = @repository.find_branch(params[:id])

    if branch && @repository.rm_branch(branch.name)
      Event.create_ref_event(@project, current_user, branch, 'rm')
    end

    respond_to do |format|
      format.html { redirect_to project_branches_path(@project) }
      format.js { render nothing: true }
    end
  end
end

app/controllers/projects/commit_controller.rb
# Controller for a specific Commit
#
# Not to be confused with CommitsController, plural.
class Projects::CommitController < Projects::ApplicationController
  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_code_access!
  before_filter :require_non_empty_project

  def show
    result = CommitLoadContext.new(project, current_user, params).execute

    @commit = result[:commit]

    if @commit.nil?
      git_not_found!
      return
    end

    @suppress_diff = result[:suppress_diff]
    @force_suppress_diff = result[:force_suppress_diff]

    @note        = result[:note]
    @line_notes  = result[:line_notes]
    @notes_count = result[:notes_count]
    @target_type = :commit
    @target_id   = @commit.id

    @comments_allowed = @reply_allowed = true
    @comments_target  = { noteable_type: 'Commit',
                          commit_id: @commit.id }

    respond_to do |format|
      format.html do
        if result[:status] == :huge_commit
          render "huge_commit" and return
        end
      end

      format.diff  { render text: @commit.to_diff }
      format.patch { render text: @commit.to_patch }
    end
  end
end

app/controllers/projects/commits_controller.rb
require "base64"

class Projects::CommitsController < Projects::ApplicationController
  include ExtractsPath

  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_code_access!
  before_filter :require_non_empty_project

  def show
    @repo = @project.repository
    @limit, @offset = (params[:limit] || 40), (params[:offset] || 0)

    @commits = @repo.commits(@ref, @path, @limit, @offset)

    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.atom { render layout: false }
    end
  end
end

app/controllers/projects/compare_controller.rb
class Projects::CompareController < Projects::ApplicationController
  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_code_access!
  before_filter :require_non_empty_project

  def index
  end

  def show
    compare = Gitlab::Git::Compare.new(@repository.raw_repository, params[:from], params[:to])

    @commits       = compare.commits
    @commit        = compare.commit
    @diffs         = compare.diffs
    @refs_are_same = compare.same
    @line_notes    = []

    diff_line_count = Commit::diff_line_count(@diffs)
    @suppress_diff = Commit::diff_suppress?(@diffs, diff_line_count) && !params[:force_show_diff]
    @force_suppress_diff = Commit::diff_force_suppress?(@diffs, diff_line_count)
  end

  def create
    redirect_to project_compare_path(@project, params[:from], params[:to])
  end
end

app/controllers/projects/deploy_keys_controller.rb
class Projects::DeployKeysController < Projects::ApplicationController
  respond_to :html

  # Authorize
  before_filter :authorize_admin_project!

  layout "project_settings"

  def index
    @enabled_keys = @project.deploy_keys.all
    @available_keys = available_keys - @enabled_keys
  end

  def show
    @key = @project.deploy_keys.find(params[:id])
  end

  def new
    @key = @project.deploy_keys.new

    respond_with(@key)
  end

  def create
    @key = DeployKey.new(params[:deploy_key])

    if @key.valid? && @project.deploy_keys << @key
      redirect_to project_deploy_keys_path(@project)
    else
      render "new"
    end
  end

  def destroy
    @key = @project.deploy_keys.find(params[:id])
    @key.destroy

    respond_to do |format|
      format.html { redirect_to project_deploy_keys_url }
      format.js { render nothing: true }
    end
  end

  def enable
    project.deploy_keys << available_keys.find(params[:id])

    redirect_to project_deploy_keys_path(@project)
  end

  def disable
    @project.deploy_keys_projects.where(deploy_key_id: params[:id]).last.destroy

    redirect_to project_deploy_keys_path(@project)
  end

  protected

  def available_keys
    @available_keys ||= current_user.accessible_deploy_keys
  end
end

app/controllers/projects/edit_tree_controller.rb
# Controller for edit a repository's file
class Projects::EditTreeController < Projects::ApplicationController
  include ExtractsPath

  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_code_access!
  before_filter :require_non_empty_project

  before_filter :edit_requirements, only: [:show, :update]

  def show
    @last_commit = Gitlab::Git::Commit.last_for_path(@project.repository, @ref, @path).sha
  end

  def update
    edit_file_action = Gitlab::Satellite::EditFileAction.new(current_user, @project, @ref, @path)
    updated_successfully = edit_file_action.commit!(
      params[:content],
      params[:commit_message],
      params[:last_commit]
    )

    if updated_successfully
      redirect_to project_blob_path(@project, @id), notice: "Your changes have been successfully commited"
    else
      flash[:notice] = "Your changes could not be commited, because the file has been changed"
      render :show
    end
  end

  private

  def edit_requirements
    @blob = Gitlab::Git::Blob.new(@repository, @commit.id, @ref, @path)

    unless @blob.exists? && @blob.text?
      redirect_to project_blob_path(@project, @id), notice: "You can only edit text files"
    end

    allowed = if project.protected_branch? @ref
                can?(current_user, :push_code_to_protected_branches, project)
              else
                can?(current_user, :push_code, project)
              end

    return access_denied! unless allowed
  end
end

app/controllers/projects/graphs_controller.rb
class Projects::GraphsController < Projects::ApplicationController
  # Authorize
  before_filter :authorize_read_project!
  before_filter :authorize_code_access!
  before_filter :require_non_empty_project

  def show
    respond_to do |format|
      format.html
      format.js do
        fetch_graph
      end
    end
  end

  private

  def fetch_graph
    @log = @project.repository.graph_log.to_json
    @success = true
  rescue => ex
    @log = []
    @success = false
  end
end

app/views/admin/projects/index.html.haml
.row
  .span4
    .admin-filter
      = form_tag admin_projects_path, method: :get, class: 'form-inline' do
        .control-group
          = label_tag :name, '项目名称:', class: 'control-label'
          .controls
            = text_field_tag :name, params[:name], class: "span2"

        .control-group
          = label_tag :owner_id, '所有者:', class: 'control-label'
          .controls
            = users_select_tag :owner_id, selected: params[:owner_id], class: 'input-large'
        .control-group
          = label_tag :public_only, '公开的', class: 'control-label'
          .controls
            = check_box_tag :public_only, 1, params[:public_only]
        .control-group
          = label_tag :with_push, 'Not empty', class: 'control-label'
          .controls
            = check_box_tag :with_push, 1, params[:with_push]
            &nbsp;
            %span.light Projects with push events
        .control-group
          = label_tag :abandoned, '遗弃', class: 'control-label'
          .controls
            = check_box_tag :abandoned, 1, params[:abandoned]
            &nbsp;
            %span.light 超过6个月没有活动的



        .form-actions
          = submit_tag "搜索", class: "btn submit btn-primary"
          = link_to "重设", admin_projects_path, class: "btn"
  .span8
    .ui-box
      .title
        Projects (#{@projects.total_count})
        .pull-right
          = link_to '创建项目', new_project_path, class: "btn btn-new"
      %ul.well-list
        - @projects.each do |project|
          %li
            - if project.public
              = public_icon
            - else
              = private_icon
            = link_to project.name_with_namespace, [:admin, project]
            .pull-right
              = link_to '修改', edit_project_path(project), id: "edit_#{dom_id(project)}", class: "btn btn-small"
              = link_to '摧毁', [project], confirm: remove_project_message(project), method: :delete, class: "btn btn-small btn-remove"
        - if @projects.blank?
          %p.nothing_here_message 0 projects matches
    = paginate @projects, theme: "gitlab"

app/views/admin/projects/show.html.haml
%h3.page-title
  项目: #{@project.name_with_namespace}
  = link_to edit_project_path(@project), class: "btn pull-right" do
    %i.icon-edit
    修改
%hr
.row
  .span6
    .ui-box
      .title
        项目信息:
      %ul.well-list
        %li
          %span.light Name:
          %strong
            = link_to @project.name, project_path(@project)
        %li
          %span.light Namespace:
          %strong
            - if @project.namespace
              = link_to @project.namespace.human_name, [:admin, @project.group || @project.owner]
            - else
              Global
        %li
          %span.light 所有者:
          %strong
            - if @project.owner
              = link_to @project.owner_name, admin_user_path(@project.owner)
            - else
              (删除)

        %li
          %span.light 创建者:
          %strong
            = @project.creator.try(:name) || '(deleted)'

        %li
          %span.light 创建于:
          %strong
            = @project.created_at.stamp("March 1, 1999")

        %li
          %span.light http:
          %strong
            = link_to @project.http_url_to_repo
        %li
          %span.light ssh:
          %strong
            = link_to @project.ssh_url_to_repo
        - if @project.repository.exists?
          %li
            %span.light fs:
            %strong
              = @repository.path_to_repo

          %li
            %span.light 是后提交:
            %strong
              = last_commit(@project)
        - else
          %li
            %span.light repository:
            %strong.cred
              不存在

        %li
          %span.light 权限:
          %strong
            - if @project.public
              %span.cblue
                %i.icon-share
                公开(Public)
            - else
              %span.cgreen
                %i.icon-lock
                私有(Private)
  .span6
    - if @group
      .ui-box
        .title
          %strong #{@group.name}
          用户组成员 (#{@group.users_groups.count})
          .pull-right
            = link_to admin_group_path(@group), class: 'btn btn-small' do
              %i.icon-edit
        %ul.well-list
          - @group.users_groups.order('group_access DESC').each do |member|
            = render 'users_groups/users_group', member: member, show_controls: false

    .ui-box
      .title
        项目成员
        %small
          (#{@project.users.count})
        .pull-right
          = link_to project_team_index_path(@project), class: "btn btn-tiny" do
            %i.icon-edit
            管理权限
      %ul.well-list.team_members
        - @project.users_projects.each do |users_project|
          - user = users_project.user
          %li.users_project
            %strong
              = link_to user.name, admin_user_path(user)
            .pull-right
              - if users_project.owner?
                %span.light 所有者
              - else
                %span.light= users_project.human_access
                = link_to project_team_member_path(@project, user), confirm: remove_from_project_team_message(@project, user), method: :delete, remote: true, class: "btn btn-small btn-remove" do
                  %i.icon-remove